---

# Derivative of the following pipeline by Lars Kellogg-Stedman
# https://github.com/larsks/hello-flask
# GPLv3

name: 'Build and publish container images'

on:
  push:
    branches:
      - tes3mp-*

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=tes3mp/server
          VERSION=$(grep "ENV TES3MP_VERSION .*" Dockerfile | awk 'NF>1{print $NF}')
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $GITHUB_REF =~ master ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm
          push: true
          tags: ${{ steps.prep.outputs.tags }}
